name: letsgamba
version: '0.6.7'
authors:
  - nichoconutzy
  - Handburger
main: me.choconutzy.letsGamba.LetsGambaPlugin
api-version: '1.21.10'
depend: [Vault]
softdepend: [GSit]

commands:
  poker:
    description: Play Texas Hold'em in Minecraft!
    usage: "/poker [start|join|leave|fold|call|raise|info]"
    aliases: [check, call, fold, raise]

