name: letsgamba
version: '0.5.20'
main: me.choconutzy.letsGamba.LetsGambaPlugin
api-version: '1.21.10'
depend: [Vault]
softdepend: [GSit]

commands:
  poker:
    description: Play Ultimate Texas Hold'em!
    usage: "/poker [join|leave|fold|call|raise|info]"
    aliases: [check, call, fold, raise]

